### PR TITLE
issue #9: allow array in more option in backuppc_hosts

### PR DESCRIPTION
**Pull request by jardleex**
Hello @HanXHX,

regarding the issue #9 i put your suggested solution into this PR. I fixed two small syntax issues and expanded the tests/test.yml as well.

Please have a look.

Thanks

Jard

### CODE REVIEW

**Comment by jardleex** [comment]
Hey,

i had to changed the tests.yml. It seems that BackupPc does not support --acl or --xattrs on rsync.
See [here](https://sourceforge.net/p/backuppc/mailman/message/34544316/) for details.

Anyway the array feature still works

**Comment by HanXHX** [comment]
It seems good. However, i want a good jinja structure. Spaces need to be a the good place. Yes you can hate me :)

Exemple: `{% if myvar %}`, not `{% if myvar%}`

**Comment by jardleex** [comment]
I got your point about the clean code, that's absolutly fine and leads to better results.
I checked the code again after i stared at it ~ 1.5 hours yesterday to find the syntax issues.

How's about that?

```
{% if item.more is defined %}
# More options...
{% for key, value in item.more.iteritems() %}
{% if value is string %}
$Conf{{ '{' }}{{ key }}{{ '}' }} = '{{ value }}';
{% else %}
$Conf{{ '{' }}{{ key }}{{ '}' }} = [
  {% for i in value %}'{{ i }}'{% if not loop.last %}, {% endif %}
{% endfor %}

];

{% endif %}
{% endfor %}
{% endif %}
```

I put the newlines arount the ] to have the result more readeable. Regarding the spaces i saw only 2 places (end line 8 and line 9). Did i miss something?

Best
Jard

**Comment by jardleex** [comment]
bump

**Pull request merged**
