### PR TITLE
added backuppc_ServerHost to optionally configure ServerHost

### PR DESCRIPTION
**Pull request by jardleex**
Hi HanHXH,

here comes another optionaly setting to adjust the ServerHost line in the BackupPC config.pl.

Best regards

Jard

### CODE REVIEW

**Comment by HanXHX** [comment]
Hi @jardleex,

I already have a similar var: `backuppc_server_name` (used to create SSH key). Can you use it for your PR?

Cheers,

HanXHX

**Comment by jardleex** [comment]
Hi @HanXHX,
i'll check that. Thanks for the hint.

Best,
Jard

**Comment by jardleex** [comment]
Hi @HanXHX,

there it is. Sorry for the confusion. I must have overseen the variable in the first place.

Best,
Jard

**Comment by jardleex** [comment]
Hi @HanXHX,
i just saw that the variable backkuppc_fetch_ssh_key (double k) got a typo. I fixed it globally in the last commit.

Best,
Jard

**Comment by HanXHX** [comment]
It sounds good. I merge it. TY @jardleex

**Pull request merged**
